controller_manager:
  ros__parameters:
    update_rate: 50  # Hz
    
    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster
      
    lid_joint_position_controller:
      type: position_controllers/JointPositionController

lid_joint_position_controller:
  ros__parameters:
    joint: lid_joint
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
    state_publish_rate: 50.0
    action_monitor_rate: 20.0
